services:
  mcp-server:
    container_name: mcp-server-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    env_file:
      - .env.prod
    command: node build/index.js
    depends_on:
      - frontend

  frontend:
    container_name: mcp-frontend-prod
    build:
      context: ./mcp-inspector-frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./mcp-inspector-frontend/.env.prod
    command: yarn start
