# Remove the 'version' line as per the warning, it's obsolete
# version: "3.9" # <-- Remove this line

volumes: # <-- ADD THIS SECTION
  frontend_node_modules: {} # Define the named volume here

services:
  mcp-server:
    container_name: mcp-server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      # Optional: Isolate node_modules for the server too if needed
      # - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    command: yarn dev
    depends_on:
      - frontend

  frontend:
    container_name: mcp-frontend-dev
    build:
      context: ./mcp-inspector-frontend
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the app code
      - ./mcp-inspector-frontend:/app
      # Use the DEFINED named volume for node_modules
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./mcp-inspector-frontend/.env.local
    command: yarn dev:docker # Keep using the non-turbopack command for now
